
resource.AddFile("sound/radio/chatter1.ogg")
resource.AddFile("sound/radio/chatter2.ogg")
resource.AddFile("sound/radio/chatter3.ogg")
resource.AddFile("sound/radio/chatter4.ogg")
resource.AddFile("sound/radio/franklin1.ogg")
resource.AddFile("sound/radio/franklin2.ogg")
resource.AddFile("sound/radio/franklin3.ogg")
resource.AddFile("sound/radio/franklin4.ogg")
resource.AddFile("sound/radio/radioalarm.ogg")
resource.AddFile("sound/radio/radioalarm2.ogg")
resource.AddFile("sound/radio/scpradio0.ogg")
resource.AddFile("sound/radio/scpradio1.ogg")
resource.AddFile("sound/radio/scpradio2.ogg")
resource.AddFile("sound/radio/scpradio3.ogg")
resource.AddFile("sound/radio/scpradio4.ogg")
resource.AddFile("sound/radio/scpradio5.ogg")
resource.AddFile("sound/radio/scpradio6.ogg")
resource.AddFile("sound/radio/scpradio7.ogg")
resource.AddFile("sound/radio/scpradio8.ogg")
resource.AddFile("sound/radio/ohgod.ogg")

print("Gamemode loaded core/server/sv_resources.lua")